version: "3.8"

services:
  api:
    build: api
    environment:
      - NODE_ENV=development
    volumes:
      - "./api:/app"
    env_file:
      - ./env/mysql.env
    ports:
      - "3001:3000"
    links:
      - db

  db:
    image: tutum/mysql:5.6
    environment:
      - ON_CREATE_DB=development_db
    env_file:
      - ./env/mysql.env
    volumes:
      - "blog-db-data:/var/lib/mysql"

volumes:
  blog-db-data:
    external: false
